services:
  - type: web
    name: goalgazer-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: NEXT_PUBLIC_API_URL
        value: "https://prediction-backend-rnub.onrender.com" # You may need this later
